theme = "adwaita-dark"
[editor]
line-number = "relative"
auto-save = true
auto-format = false
end-of-line-diagnostics = "hint"
true-color = true

[editor.statusline]
left = ["mode","spinner","separator","read-only-indicator","file-modification-indicator"]
center = ["separator","file-absolute-path","separator","file-type","separator"]

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
 display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"
nbsp = "all"

[keys.normal]
C-s = ":update"
C-x = ":x"
C-p = "file_picker"
A-z = ":toggle soft-wrap.enable"
A-q = ":reflow"
F5 = ":reload"

C-h = "jump_view_left"
C-l = "jump_view_right"
C-k = "jump_view_up"
C-j = "jump_view_down"

[keys.normal."'"]
f = ":format"
i = ":toggle lsp.display-inlay-hints"

[keys.normal.Z]
Z = ":write-quit-all"

[keys.insert.j]
k = "normal_mode"
